x-veld:
  executable:
    about:
      description: "prints information about the python intepreter within the docker container."
      scope: "testing"

services:
  veld:
    build: .
    volumes:
      - ./src/:/veld/executable/
    command: python /veld/executable/test.py

